### ISSUE TITLE
Push access

### ISSUE THREAD

**Issue by anmol27katyani** [raghavdubey/INTERN-PRACTICE-QUESTION#13]
@raghavdubey I think i have lost my push access to this repository.
Any reason behind this sir?

**Comment by raghavdubey** [comment]
Hello @mishraanmol , I'm happy you noticed that actually, we at the company decided that all your push request will firstly be reviewed so that you work on all things very well.

You must understand our concern boy.
We will be giving you weekly feedback from today.

You will now be seeing a lot of changes soon but all will make the flow smooth and you will surely like them and appreciate too.

**Comment by anmol27katyani** [comment]
Ok @raghavdubey 
I can understand that. Thanks for replying.
